baseURL = "https://chheis.github.io/website-hephaestus-test/"
languageCode = "en-us"
title = "Eclipse Hepheistos"
theme = "hugo-solstice-theme"
enableRobotsTXT = true
canonifyURLs = false
relativeURLs = false

[pagination]
  pagerSize = 10

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[params]
  description = "Eclipse Hepheistos provides open SDV tooling for building, integrating, and validating software-defined vehicle development workflows."
  seo_title_suffix = " | Eclipse Hepheistos"
  subtitle = "Eclipse Foundation"
  
[params.author]
  name = "Eclipse Hepheistos"
  website = "https://projects.eclipse.org/"
  email = "hepheistos@eclipse.org"
  twitter = "EclipseFdn"

[[params.styles]]
  url = "css/neptune.css"
  cache = true

[[params.scripts]]
  url = "js/neptune.js"
  cache = true
